version: 0.1
default:
  deploy:
    parameters:
      parameter_overrides:
        - "Stage=local"
        - "LocalDev=true"
      stack_name: my-app-stack
      resolve_s3: true
      s3_prefix: sam-app
      region: us-west-2
      confirm_changeset: true 
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      disable_rollback: false
      image_repositories: []